# Common issues in manuscript reviews
# Submitted by Haley Hedlin
c("No limitations described",
  "Figure legends missing",
  "Statistical software not specified",
  "Acronym not defined",
  "Not clear what test used to calculate a result",
  "Table/figure not mentioned in results",
  "Statistical model not clear",
  "CONSORT diagram missing",
  "Inclusion/exclusion criteria unclear",
  "Not clear whether analyses chosen a priori",
  "Handling of missing data not described",
  "No confidence intervals provided",
  "Not clear if model assumptions were checked",
  "Bad graphs (eg pie charts, 3d bar charts)",
  "Hypotheses not clear",
  "Level of significance not reported",
  "Unclear statistical methods",
  "Unclear or missing baseline characteristics/Table 1",
  "Improper use of statistical terms",
  "Not clear if significant results are clinically or statistically significant",
  "Measured values not expressed to the appropriate precision",
  "Multiple testing not appropriately handled",
  "Unclear what is presented in table cells",
  "Missing reference where citation needed"
)
